/* This code was generated by phptoc.c */
/* {{{ Includes */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "phpjs.h"
#include "php_ini.h"
#include "ext/standard/info.h"
#include "zend.h"
#include "zend_API.h"
#include "zend_exceptions.h"
#include "zend_operators.h"
#include "zend_constants.h"
#include "zend_ini.h"
#include "zend_interfaces.h"

/* }}} */
/* {{{ Class entry pointers */

PHPAPI zend_class_entry *phpjs_JSException_ptr;
PHPAPI zend_class_entry *phpjs_JSFunctionWrapper_ptr;
PHPAPI zend_class_entry *phpjs_JS_ptr;

static zend_class_entry* _find_class(char* name TSRMLS_DC)
{
  zend_class_entry **pce = NULL;
  zend_lookup_class(name, strlen(name), &pce TSRMLS_CC);
  return pce ? *pce : NULL;
}

/* }}} */
/* {{{ Methods for class JSException */

// final private function __clone()
ZEND_METHOD(JSException, __clone)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// public function __construct($message, $code, $previous)
ZEND_METHOD(JSException, __construct)
{
  zval* a_message;
  zval* a_code;
  zval* a_previous;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zzz", &a_message, &a_code, &a_previous) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_message, 1 TSRMLS_CC);
  php_var_dump(&a_code, 1 TSRMLS_CC);
  php_var_dump(&a_previous, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// final public function getMessage()
ZEND_METHOD(JSException, getMessage)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// final public function getCode()
ZEND_METHOD(JSException, getCode)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// final public function getFile()
ZEND_METHOD(JSException, getFile)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// final public function getLine()
ZEND_METHOD(JSException, getLine)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// final public function getTrace()
ZEND_METHOD(JSException, getTrace)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// final public function getPrevious()
ZEND_METHOD(JSException, getPrevious)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// final public function getTraceAsString()
ZEND_METHOD(JSException, getTraceAsString)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

// public function __toString()
ZEND_METHOD(JSException, __toString)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSException_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

/* }}} */
/* {{{ Methods for class JSFunctionWrapper */

// public function __invoke()
ZEND_METHOD(JSFunctionWrapper, __invoke)
{
  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JSFunctionWrapper_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters_none() == FAILURE) {
    return;
  }

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  RETURN_FALSE;
}

/* }}} */
/* {{{ Methods for class JS */

// public function load($file)
ZEND_METHOD(JS, load)
{
  zval* a_file;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &a_file) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_file, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function offsetExists($offset)
ZEND_METHOD(JS, offsetExists)
{
  zval* a_offset;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &a_offset) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_offset, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function offsetGet($offset)
ZEND_METHOD(JS, offsetGet)
{
  zval* a_offset;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &a_offset) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_offset, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function offsetSet($offset, $value)
ZEND_METHOD(JS, offsetSet)
{
  zval* a_offset;
  zval* a_value;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zz", &a_offset, &a_value) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_offset, 1 TSRMLS_CC);
  php_var_dump(&a_value, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function offsetUnset($offset)
ZEND_METHOD(JS, offsetUnset)
{
  zval* a_offset;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &a_offset) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_offset, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function export($name)
ZEND_METHOD(JS, export)
{
  zval* a_name;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &a_name) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_name, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function __get($name)
ZEND_METHOD(JS, __get)
{
  zval* a_name;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &a_name) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_name, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function __set($name, $value)
ZEND_METHOD(JS, __set)
{
  zval* a_name;
  zval* a_value;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zz", &a_name, &a_value) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_name, 1 TSRMLS_CC);
  php_var_dump(&a_value, 1 TSRMLS_CC);
  RETURN_FALSE;
}

// public function __call($name, $args)
ZEND_METHOD(JS, __call)
{
  zval* a_name;
  zval* a_args;

  if (!this_ptr || !instanceof_function(Z_OBJCE_P(this_ptr), phpjs_JS_ptr TSRMLS_CC)) {
    zend_error(E_ERROR, "%s() cannot be called statically", get_active_function_name(TSRMLS_C));
    return;
  }

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zz", &a_name, &a_args) == FAILURE)
    return;

  const char* space;
  php_printf("method %s::%s was called\n", get_active_class_name(&space TSRMLS_CC), get_active_function_name(TSRMLS_CC));
  php_var_dump(&a_name, 1 TSRMLS_CC);
  php_var_dump(&a_args, 1 TSRMLS_CC);
  RETURN_FALSE;
}

/* }}} */
/* {{{ Global functions */

/* }}} */
/* {{{ Method tables for classes */

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException___clone, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException___construct, 0, 0, 0)
  ZEND_ARG_INFO(0, message)
  ZEND_ARG_INFO(0, code)
  ZEND_ARG_INFO(0, previous)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getMessage, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getCode, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getFile, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getLine, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getTrace, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getPrevious, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException_getTraceAsString, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSException___toString, 0, 0, 0)
ZEND_END_ARG_INFO()

static zend_function_entry phpjs_JSException_functions[] = {
  ZEND_ME(JSException, __clone, ai_phpjs_JSException___clone, ZEND_ACC_FINAL|ZEND_ACC_PRIVATE)
  ZEND_ME(JSException, __construct, ai_phpjs_JSException___construct, ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getMessage, ai_phpjs_JSException_getMessage, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getCode, ai_phpjs_JSException_getCode, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getFile, ai_phpjs_JSException_getFile, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getLine, ai_phpjs_JSException_getLine, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getTrace, ai_phpjs_JSException_getTrace, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getPrevious, ai_phpjs_JSException_getPrevious, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, getTraceAsString, ai_phpjs_JSException_getTraceAsString, ZEND_ACC_FINAL|ZEND_ACC_PUBLIC)
  ZEND_ME(JSException, __toString, ai_phpjs_JSException___toString, ZEND_ACC_PUBLIC)
  ZEND_FE_END
};

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JSFunctionWrapper___invoke, 0, 0, 0)
ZEND_END_ARG_INFO()

static zend_function_entry phpjs_JSFunctionWrapper_functions[] = {
  ZEND_ME(JSFunctionWrapper, __invoke, ai_phpjs_JSFunctionWrapper___invoke, ZEND_ACC_PUBLIC)
  ZEND_FE_END
};

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS_load, 0, 0, 1)
  ZEND_ARG_INFO(0, file)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS_offsetExists, 0, 0, 1)
  ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS_offsetGet, 0, 0, 1)
  ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS_offsetSet, 0, 0, 2)
  ZEND_ARG_INFO(0, offset)
  ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS_offsetUnset, 0, 0, 1)
  ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS_export, 0, 0, 1)
  ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS___get, 0, 0, 1)
  ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS___set, 0, 0, 2)
  ZEND_ARG_INFO(0, name)
  ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(ai_phpjs_JS___call, 0, 0, 2)
  ZEND_ARG_INFO(0, name)
  ZEND_ARG_INFO(0, args)
ZEND_END_ARG_INFO()

static zend_function_entry phpjs_JS_functions[] = {
  ZEND_ME(JS, load, ai_phpjs_JS_load, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, offsetExists, ai_phpjs_JS_offsetExists, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, offsetGet, ai_phpjs_JS_offsetGet, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, offsetSet, ai_phpjs_JS_offsetSet, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, offsetUnset, ai_phpjs_JS_offsetUnset, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, export, ai_phpjs_JS_export, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, __get, ai_phpjs_JS___get, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, __set, ai_phpjs_JS___set, ZEND_ACC_PUBLIC)
  ZEND_ME(JS, __call, ai_phpjs_JS___call, ZEND_ACC_PUBLIC)
  ZEND_FE_END
};

/* }}} */
/* {{{ Function table */

static zend_function_entry phpjs_functions[] = {
  {NULL, NULL, NULL}
};

/* }}} */
/* {{{ Init */

PHP_MINIT_FUNCTION(phpjs)
{
  zend_class_entry _ce, *_if;
  zval* _val;
  
  INIT_CLASS_ENTRY(_ce, "JSException", phpjs_JSException_functions);
  phpjs_JSException_ptr = zend_register_internal_class_ex(&_ce, NULL, "Exception" TSRMLS_CC);
  zend_declare_property_string(phpjs_JSException_ptr, _S("message"), "", ZEND_ACC_PROTECTED TSRMLS_CC);
  zend_declare_property_long(phpjs_JSException_ptr, _S("code"), 0, ZEND_ACC_PROTECTED TSRMLS_CC);
  zend_declare_property_null(phpjs_JSException_ptr, _S("file"), ZEND_ACC_PROTECTED TSRMLS_CC);
  zend_declare_property_null(phpjs_JSException_ptr, _S("line"), ZEND_ACC_PROTECTED TSRMLS_CC);

  INIT_CLASS_ENTRY(_ce, "JSFunctionWrapper", phpjs_JSFunctionWrapper_functions);
  phpjs_JSFunctionWrapper_ptr = zend_register_internal_class(&_ce TSRMLS_CC);

  INIT_CLASS_ENTRY(_ce, "JS", phpjs_JS_functions);
  phpjs_JS_ptr = zend_register_internal_class(&_ce TSRMLS_CC);
  if ((_if = _find_class("ArrayAccess" TSRMLS_CC)))
    zend_do_implement_interface(phpjs_JS_ptr, _if TSRMLS_CC);

  return SUCCESS;
}

/* }}} */
/* {{{ Info */

PHP_MINFO_FUNCTION(phpjs)
{
  php_info_print_table_start();
  php_info_print_table_header(2, "phpjs", "enabled");
  php_info_print_table_row(2, "Version", "1.0");
  php_info_print_table_end();
}

/* }}} */
/* {{{ Module entry */

zend_module_entry phpjs_module_entry = {
  STANDARD_MODULE_HEADER,
  "phpjs",
  phpjs_functions,
  PHP_MINIT(phpjs),
  NULL,
  NULL,
  NULL,
  PHP_MINFO(phpjs),
  "1.0",
  STANDARD_MODULE_PROPERTIES
};

#ifdef COMPILE_DL_PHPJS
ZEND_GET_MODULE(phpjs)
#endif

/* }}} */
